{
    "id": "CVE-2025-48432",
    "product": "Django",
    "version": "4.2 ",
    "vulnerability": [
        "CWE-117 Improper Output Neutralization for Logs"
    ],
    "description": "An issue was discovered in Django 5.2 before 5.2.3, 5.1 before 5.1.11, and 4.2 before 4.2.23. Internal HTTP response logging does not escape request.path, which allows remote attackers to potentially manipulate log output via crafted URLs. This may lead to log injection or forgery when logs are viewed in terminals or processed by external systems.",
    "poc": {
        "reference": [
            "No PoCs from references."
        ],
        "github": [
            "https://github.com/ARPSyndicate/cve-scores",
            "https://github.com/ch4n3-yoon/ch4n3-yoon",
            "https://github.com/graydonhope/VulnerabilityScanner",
            "https://github.com/thexnumb/thexwriteup",
            "https://github.com/w4zu/Debian_security"
        ]
    }
}