{
    "id": "CVE-2023-29824",
    "product": "n/a",
    "version": "0 ",
    "vulnerability": [
        "n/a"
    ],
    "description": "A use-after-free issue was discovered in Py_FindObjects() function in SciPy versions prior to 1.8.0. NOTE: the vendor and discoverer indicate that this is not a security issue.",
    "poc": {
        "reference": [
            "https://github.com/scipy/scipy/issues/14713",
            "https://github.com/scipy/scipy/issues/14713#issuecomment-1629468565"
        ],
        "github": [
            "https://github.com/vin01/bogus-cves"
        ]
    }
}