{
    "id": "CVE-2023-39661",
    "product": "n/a",
    "version": "n/a",
    "vulnerability": [
        "n/a"
    ],
    "description": "An issue in pandas-ai v.0.9.1 and before allows a remote attacker to execute arbitrary code via the _is_jailbreak function.",
    "poc": {
        "reference": [
            "https://github.com/gventuri/pandas-ai/issues/410"
        ],
        "github": [
            "No PoCs found on GitHub currently."
        ]
    }
}