{
    "id": "CVE-2024-53432",
    "product": "n/a",
    "version": "n/a",
    "vulnerability": [
        "n/a"
    ],
    "description": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes due to an uncaught std::out_of_range exception in PCLPointCloud2::at. This issue could potentially be exploited to cause a denial-of-service (DoS) attack when processing untrusted PLY files.",
    "poc": {
        "reference": [
            "https://github.com/PointCloudLibrary/pcl/issues/6162"
        ],
        "github": [
            "No PoCs found on GitHub currently."
        ]
    }
}