{
    "id": "CVE-2019-20431",
    "product": "n/a",
    "version": "n/a",
    "vulnerability": [
        "n/a"
    ],
    "description": "In the Lustre file system before 2.12.3, the ptlrpc module has an osd_map_remote_to_local out-of-bounds access and panic due to the lack of validation for specific fields of packets sent by a client. osd_bufs_get in the osd_ldiskfs module does not validate a certain length value.",
    "poc": {
        "reference": [
            "http://lustre.org/",
            "http://wiki.lustre.org/Lustre_2.12.3_Changelog"
        ],
        "github": [
            "No PoCs found on GitHub currently."
        ]
    }
}