{
    "id": "CVE-2020-24372",
    "product": "n/a",
    "version": "n/a ",
    "vulnerability": [
        "n/a"
    ],
    "description": "LuaJIT through 2.1.0-beta3 has an out-of-bounds read in lj_err_run in lj_err.c.",
    "poc": {
        "reference": [
            "https://github.com/LuaJIT/LuaJIT/issues/603"
        ],
        "github": [
            "https://github.com/w4zu/Debian_security"
        ]
    }
}