{
    "id": "CVE-2012-2135",
    "product": "n/a",
    "version": "n/a ",
    "vulnerability": [
        "n/a"
    ],
    "description": "The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors.",
    "poc": {
        "reference": [
            "http://www.ubuntu.com/usn/USN-1616-1"
        ],
        "github": [
            "No PoCs found on GitHub currently."
        ]
    }
}